server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/activitidemo?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 11111111





